[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[functions]
  node_bundler = "esbuild"
  included_files = ["lib/**"]
  external_node_modules = ["postgres","jsonwebtoken"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
